# Master YAML for Python packages

name: Main

# Controls when the action will run.
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PY_VERSION: 3.8

  # this is used for coverage testing and to define location of publish Sphinx documentation.
  PACKAGE_NAME: pyinstaller_test

jobs:
  bootstrap_deps:
    name: bootstrap dependencies
    # The type of runner that the job will run on
    runs-on: [windows-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PY_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install setuptools wheel twine build 
          pip download . --dest ${{ runner.temp }}\packages

      - name: Upload dependencies artifact
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ${{ runner.temp }}\packages\

